### ISSUE TITLE
First Element on the '@' is not being selected

### ISSUE THREAD

**Issue by sarger** [avcs06/AutoSuggest#2]
I must say this is a good project, here is how to reproduce the issue
1. Type '@'
2. When the list appears, move the mouse curser to the second element (Peter john)
3. Move the curser to the 1st element (Chandrasekhar Ambula V)
4. Click the 1st element

**Comment by avcs06** [comment]
@sarger  Thank you for reporting the issue, i will fix it this weekend

**Comment by moussa-b** [comment]
@sarger yes I reproduce the same issue. @avcs06 thank you for this great lib. Any update to know when this issue will be fixed?

**Comment by avcs06** [comment]
Fixed the issue in v1.2.0-beta

https://github.com/avcs06/AutoSuggest/commit/bf604ba5efd8f4ae447b8ff89cfe5721cc0369a9
