### ISSUE TITLE
Would be usefull to add a configuration parameter to limit the length of the dropdown??

### ISSUE THREAD

**Issue by moussa-b** [avcs06/AutoSuggest#4]
I think this feature may be usefull, especially when options of the dropdown comes from a webservice that may return hunders of data

**Comment by avcs06** [comment]
Added a new parameter `maxSuggestions` to limit the number of suggestions shown in dropdown.

https://github.com/avcs06/AutoSuggest/commit/8e8014fa188a2616f2447fb1454ce0f085513ace

**Comment by moussa-b** [comment]
Hi @avcs06 thanx a lot for beeing so prompt to answer our needs :)
